---
- name: configuring partitions with lvm
  hosts: testing
  tasks:
  - name: creating volume group
    lvg:
      vg: vg1
      pvs: /dev/sdb1, /dev/sdb2
  - name: creating logical volume
    lvol:
      vg: vg1
      lv: lv1
      size: 1G
  - name: making filesystem
    filesystem:
      fstype: ext4
      dev: /dev/vg1/lv1
  - name: mounting
    mount: 
      name: /lvmount
      src: /dev/vg1/lv1
      fstype: ext4
      state: mounted
